import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { headers } from "next/headers";

import { Navbar } from "@/app/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = headers().get("x-pathname");

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
          <Navbar pathname={pathname} />
        </header>
        {children}
      </body>
    </html>
  );
}
